### ISSUE TITLE
default.auth is not a function && no Docusaurus route context found errors

### ISSUE THREAD

**Issue by Isaac-Tait** [massoudmaboudi/docusaurus-auth-firebase#6]
I am getting the following errors. Most likely this is a user error and not a bug - just need some guidance on tracking down where the issue(s) are. Errors 1 & 2 are cropping up in localhost. I am able to deploy the repo fine to Vercel but the domain returns an error (number 3 below)

Error 1:

```
firebase_compat_app__WEBPACK_IMPORTED_MODULE_1__.default.auth is not a function
TypeError: firebase_compat_app__WEBPACK_IMPORTED_MODULE_1__.default.auth is not a function
    at eval (webpack-internal:///./src/utils/utils.js:10:281)
    at invokePassiveEffectCreate (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23482:20)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at flushPassiveEffectsImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23569:9)
    at unstable_runWithPriority (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:468:12)
    at runWithPriority$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11276:10)
    at flushPassiveEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23442:14)
    at eval (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23319:11)
```

Error 2

```
Unexpected: no Docusaurus route context found
    at useRouteContext (webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/useRouteContext.js:12:162)
    at PluginHtmlClassNameProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/metadataUtils.js:30:143)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14985:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:17811:13)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at beginWork$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23959:7)
    at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22774:12)
```

Error 3

I am able to deploy the repo to Vercel and it builds fine. However, when I visit the Vercel assigned domain I get this error message:

```
This page crashed
Try again
fn.auth is not a function
```

**Comment by Isaac-Tait** [comment]
Is this related to the "new" modular SDK? https://stackoverflow.com/questions/69055885/typeerror-fire-webpack-imported-module-1-default-auth-is-not-a-function
